#!/bin/bash

source pull-dependencies.lib

download lib http://nlp.stanford.edu/software/stanford-corenlp-full-2015-04-20.zip
if [ ! -e lib/stanford-corenlp-full-2015-04-20 ]; then
    cd lib;
    unzip stanford-corenlp-full-2015-04-20.zip
    cd ..;
fi;
download lib http://central.maven.org/maven2/junit/junit/4.11/junit-4.11.jar
download lib https://jdbc.postgresql.org/download/postgresql-9.4-1204.jdbc42.jar
download lib http://search.maven.org/remotecontent?filepath=com/opencsv/opencsv/3.6/opencsv-3.6.jar


pipPackage twitter
